name: CD Pipeline

on:
  push:
    tags:
      - 'v*server'

jobs:
  build-nix:
    env:
      IN_PIPELINE: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        type: [ubuntu-x64, ubuntu-x86, armv7, aarch64]
        include:
          - type: ubuntu-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: x86_64-linux-Fusion-server
            path: target/x86_64-unknown-linux-musl/release/Fusion-server
            pkg_config_path: /usr/lib/x86_64-linux-gnu/pkgconfig
          - type: ubuntu-x86
            os: ubuntu-latest
            target: i686-unknown-linux-musl
            name: x86-linux-Fusion-server
            path: target/i686-unknown-linux-musl/release/Fusion-server
            pkg_config_path: /usr/lib/i686-linux-gnu/pkgconfig
          - type: armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            name: armv7-linux-Fusion-server
            path: target/armv7-unknown-linux-gnueabihf/release/Fusion-server
            pkg_config_path: /usr/lib/x86_64-linux-gnu/pkgconfig
          - type: aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: aarch64-linux-Fusion-server
            path: target/aarch64-unknown-linux-gnu/release/Fusion-server
            pkg_config_path: /usr/lib/x86_64-linux-gnu/pkgconfig
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Build tar.gz for homebrew installs
        if: matrix.type == 'ubuntu-x64'
        run: |
          tar czf ${{ matrix.name }}.tar.gz -C target/x86_64-unknown-linux-musl/release Fusion-server
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
      - uses: actions/upload-artifact@v4
        if: matrix.type == 'ubuntu-x64'
        with:
          name: ${{ matrix.name }}.tar.gz
          path: ${{ matrix.name }}.tar.gz

  build-macos:
    env:
      IN_PIPELINE: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: x86_64-apple-darwin
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Build tar.gz for homebrew installs
        run: |
          tar czf x86_64-macos-Fusion-server.tar.gz -C target/x86_64-apple-darwin/release Fusion-server
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-macos-Fusion-server
          path: target/x86_64-apple-darwin/release/Fusion-server
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-macos-Fusion-server.tar.gz
          path: x86_64-macos-Fusion-server.tar.gz

  build-macos-aarch64:
    env:
      IN_PIPELINE: true
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: aarch64-apple-darwin
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Build tar.gz for homebrew installs
        run: |
          tar czf aarch64-macos-Fusion-server.tar.gz -C target/aarch64-apple-darwin/release Fusion-server
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-macos-Fusion-server
          path: target/aarch64-apple-darwin/release/Fusion-server
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-macos-Fusion-server.tar.gz
          path: aarch64-macos-Fusion-server.tar.gz

  build-windows:
    env:
      IN_PIPELINE: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        type: [windows-x64, windows-x86]
        include:
          - type: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            name: x86_64-windows-Fusion-server.exe
            path: target\x86_64-pc-windows-msvc\release\Fusion-server.exe
          - type: windows-x86
            os: windows-latest
            target: i686-pc-windows-msvc
            name: x86-windows-Fusion-server.exe
            path: target\i686-pc-windows-msvc\release\Fusion-server.exe
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target:  ${{ matrix.target }}
          args: "--locked --release"
          strip: true
          toolchain: stable
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}